# 日志配置
logging:
  level:
    com.bitactor: debug
    org.springframework: info
spring:
  bitactor:
    cluster:
      # 注册中心配置 默认 nacos 支持 backup
      registry:
        host: 127.0.0.1
        port: 8848
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # mongo 配置
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bitactor
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    database: 10